export function Home() {
    return (
        <h2>
            HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA
            ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO
            HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA
            ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO HOLA ANGO{' '}
        </h2>
    );
}
